#pinentry
pinentry-program /usr/bin/pinentry

#caches
default-cache-ttl 600
max-cache-ttl 7200

#standard socket
use-standard-socket

#ssh
enable-ssh-support

#debugging
#debug-all
#debug-level basic
#log-file /home/jmullins/.gnupg/.gpg-agent.log
